In [12]:
#PARTE 1

In [9]:

import pandas as pd
FILE_PATH = "vendas_quitanda.csv"
df = pd.read_csv(FILE_PATH,sep=";")
df
#Linhas: 510, Colunas: 8.

,ID,Nome,Idade,Cidade,Produto,Preço,Quantidade,Data_Compra
0,1,Mariana,48.0,FORTALEZA,Tablet,"2010,87",7,30-05-2024
1,2,Bruno,42.0,RIO DE JANEIRO,Teclado,NaN,6,12-04-2025
2,3,Ana,54.0,RIO DE JANEIRO,Monitor,3619.29,2,10-12-2022
3,4,Carlos,62.0,CURITIBA,Teclado,40415.9,8,31-12-2022
4,5,Mariana,60.0,CURITIBA,Notebook,716.66,8,14-09-2023
...,...,...,...,...,...,...,...,...
505,395,Bruno,46.0,CURITIBA,Headset,3321.2,2,24-08-2023
506,378,Mariana,62.0,MANAUS,Tablet,3282.26,3,19-05-2025
507,125,João,24.0,MANAUS,Headset,4529.67,5,19-02-2025
508,69,João,25.0,BELO HORIZONTE,Headset,31440.9,8,01-02-2024
509,451,Carlos,56.0,SALVADOR,Monitor,3383.77,8,04-02-2024

In [11]:
df.dtypes 
#Preço deveria ser float64, contudo devido à inconsistência entre pontos e vírgulas na inserção de valores, o pandas reconheceu como str.

ID               int64
Nome               str
Idade          float64
Cidade             str
Produto            str
Preço              str
Quantidade       int64
Data_Compra        str
dtype: object

In [ ]:
#PARTE 2

In [15]:
df.isnull().sum()
#Quantidade de valores nulos em cada coluna.

ID              0
Nome            0
Idade          21
Cidade          0
Produto         0
Preço          37
Quantidade      0
Data_Compra     0
dtype: int64

In [19]:
df['Cidade'].unique()
# Possui tanto apenas maiúsculos como apenas minúsculos.

<StringArray>
[     'FORTALEZA', 'RIO DE JANEIRO',       'CURITIBA',       'SALVADOR',
   'PORTO ALEGRE',      'SÃO PAULO',       'curitiba',         'MANAUS',
 'BELO HORIZONTE', 'rio de janeiro', 'belo horizonte',   'porto alegre',
       'salvador',         'manaus',      'fortaleza',      'são paulo']
Length: 16, dtype: str

In [24]:
df['Preço'].unique()
# Não, pois é de tipo string, pois possui 2 formatos diferentes de formatação (com . e com ,)

<StringArray>
['2010,87',       nan, '3619.29', '40415.9',  '716.66', '2388.44', '2363.09',
 '2080.54', '4229,63', '3101.25',
 ...
 '4177,57', '4066.96',  '529.69', '2479.54', '2815.44', '1176.08', '3209.09',
 '3474.99', '3444,96', '31440.9']
Length: 466, dtype: str

In [27]:
df['Data_Compra']
#Não está em datas, mas sim em str, que torna impossível agrupamento temporal,amostragem, etc.

0      30-05-2024
1      12-04-2025
2      10-12-2022
3      31-12-2022
4      14-09-2023
          ...
505    24-08-2023
506    19-05-2025
507    19-02-2025
508    01-02-2024
509    04-02-2024
Name: Data_Compra, Length: 510, dtype: str

In [ ]:
# PARTE 3

In [29]:
df['Idade'].describe()
#Fazem sentido contudo poderiam ser int.

count    489.000000
mean      44.274029
std       15.320034
min       18.000000
25%       31.000000
50%       44.000000
75%       58.000000
max       70.000000
Name: Idade, dtype: float64

In [31]:
df['Produto'].describe()
# Mais comprado: Smartphone.

count            510
unique             7
top       Smartphone
freq              85
Name: Produto, dtype: object

In [35]:
df['Preço'].describe()

count         473
unique        465
top       4035.86
freq            2
Name: Preço, dtype: object

In [34]:
df['Preço'].min()
#Mais alto: 4035.85, Mais baixo: 1006,33.

'1006,33'

In [ ]:
# PARTE 4

In [41]:
#Hipótese 1: Alguma cidade se destaca na compra de um produto específico?
pd.crosstab(df['Cidade'],df['Produto'])
# Belo Horizonte se destaca na compra de headsets.
# Curitiba, Notebooks.
# Fortaleza, Tablets.
# Manaus, Teclados.
# Porto Alegre, Smartphones.
# Entre outros...

Produto         Headset  Monitor  Mouse  Notebook  Smartphone  Tablet  Teclado
Cidade
BELO HORIZONTE       16        8      5         9           6       8        7
CURITIBA              9        7     10        12           2       9        8
FORTALEZA             3        4     12         9          10      13        5
MANAUS                9        6      8         8           9       9       10
PORTO ALEGRE          6        6     10        11          15      10        9
RIO DE JANEIRO        3       10      8         8          15       7        3
SALVADOR              9       10     10         7          13       7        8
SÃO PAULO             4        6      8         9           5       7        8
belo horizonte        0        0      2         0           2       1        2
curitiba              0        1      0         1           2       2        0
fortaleza             0        1      0         2           1       0        1
manaus                0        0      1         0           1       1        1
porto alegre          4        2      0         0           1       1        2
rio de janeiro        0        1      2         1           1       0        2
salvador              0        1      3         0           1       0        0
são paulo             0        2      0         0           1       0        0