# 1

In [98]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,RobustScaler,StandardScaler
df=pd.read_csv('adult.data',sep=',')
df.columns=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income']
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

# 2
- Todos possuem espaço extra no início de alguns, mas sem mudanças de capitalização nem de grafia.

In [70]:
df['workclass'].unique()

<StringArray>
[' Self-emp-not-inc',          ' Private',        ' State-gov',
      ' Federal-gov',        ' Local-gov',                ' ?',
     ' Self-emp-inc',      ' Without-pay',     ' Never-worked']
Length: 9, dtype: str

In [48]:
df['fnlwgt'].unique()

array([ 83311, 215646, 234721, ...,  34066,  84661, 257302],
      shape=(21647,))

In [49]:
df['education'].unique()

<StringArray>
[   ' Bachelors',      ' HS-grad',         ' 11th',      ' Masters',
          ' 9th', ' Some-college',   ' Assoc-acdm',    ' Assoc-voc',
      ' 7th-8th',    ' Doctorate',  ' Prof-school',      ' 5th-6th',
         ' 10th',      ' 1st-4th',    ' Preschool',         ' 12th']
Length: 16, dtype: str

In [50]:
df['education-num'].unique()

array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8])

In [51]:
df['marital-status'].unique()

<StringArray>
[   ' Married-civ-spouse',              ' Divorced', ' Married-spouse-absent',
         ' Never-married',             ' Separated',     ' Married-AF-spouse',
               ' Widowed']
Length: 7, dtype: str

In [52]:
df['occupation'].unique()

<StringArray>
[  ' Exec-managerial', ' Handlers-cleaners',    ' Prof-specialty',
     ' Other-service',      ' Adm-clerical',             ' Sales',
      ' Craft-repair',  ' Transport-moving',   ' Farming-fishing',
 ' Machine-op-inspct',      ' Tech-support',                 ' ?',
   ' Protective-serv',      ' Armed-Forces',   ' Priv-house-serv']
Length: 15, dtype: str

In [53]:
df['relationship'].unique()

<StringArray>
[       ' Husband',  ' Not-in-family',           ' Wife',      ' Own-child',
      ' Unmarried', ' Other-relative']
Length: 6, dtype: str

In [54]:
df['race'].unique()

<StringArray>
[' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo', ' Other']
Length: 5, dtype: str

In [55]:
df['sex'].unique()

<StringArray>
[' Male', ' Female']
Length: 2, dtype: str

In [65]:
df['capital-gain'].unique()

array([    0, 14084,  5178,  5013,  2407, 14344, 15024,  7688, 34095,
        4064,  4386,  7298,  1409,  3674,  1055,  3464,  2050,  2176,
        2174,   594, 20051,  6849,  4101,  1111,  8614,  3411,  2597,
       25236,  4650,  9386,  2463,  3103, 10605,  2964,  3325,  2580,
        3471,  4865, 99999,  6514,  1471,  2329,  2105,  2885, 25124,
       10520,  2202,  2961, 27828,  6767,  2228,  1506, 13550,  2635,
        5556,  4787,  3781,  3137,  3818,  3942,   914,   401,  2829,
        2977,  4934,  2062,  2354,  5455, 15020,  1424,  3273, 22040,
        4416,  3908, 10566,   991,  4931,  1086,  7430,  6497,   114,
        7896,  2346,  3418,  3432,  2907,  1151,  2414,  2290, 15831,
       41310,  4508,  2538,  3456,  6418,  1848,  3887,  5721,  9562,
        1455,  2036,  1831, 11678,  2936,  2993,  7443,  6360,  1797,
        1173,  4687,  6723,  2009,  6097,  2653,  1639, 18481,  7978,
        2387,  5060])

In [57]:
df['capital-loss'].unique()

array([   0, 2042, 1408, 1902, 1573, 1887, 1719, 1762, 1564, 2179, 1816,
       1980, 1977, 1876, 1340, 2206, 1741, 1485, 2339, 2415, 1380, 1721,
       2051, 2377, 1669, 2352, 1672,  653, 2392, 1504, 2001, 1590, 1651,
       1628, 1848, 1740, 2002, 1579, 2258, 1602,  419, 2547, 2174, 2205,
       1726, 2444, 1138, 2238,  625,  213, 1539,  880, 1668, 1092, 1594,
       3004, 2231, 1844,  810, 2824, 2559, 2057, 1974,  974, 2149, 1825,
       1735, 1258, 2129, 2603, 2282,  323, 4356, 2246, 1617, 1648, 2489,
       3770, 1755, 3683, 2267, 2080, 2457,  155, 3900, 2201, 1944, 2467,
       2163, 2754, 2472, 1411])

In [58]:
df['hours-per-week'].unique()

array([13, 40, 16, 45, 50, 80, 30, 35, 60, 20, 52, 44, 15, 25, 38, 43, 55,
       48, 58, 32, 70,  2, 22, 56, 41, 28, 36, 24, 46, 42, 12, 65,  1, 10,
       34, 75, 98, 33, 54,  8,  6, 64, 19, 18, 72,  5,  9, 47, 37, 21, 26,
       14,  4, 59,  7, 99, 53, 39, 62, 57, 78, 90, 66, 11, 49, 84,  3, 17,
       68, 27, 85, 31, 51, 77, 63, 23, 87, 88, 73, 89, 97, 94, 29, 96, 67,
       82, 86, 91, 81, 76, 92, 61, 74, 95])

In [59]:
df['native-country'].unique()

<StringArray>
[             ' United-States',                       ' Cuba',
                    ' Jamaica',                      ' India',
                          ' ?',                     ' Mexico',
                      ' South',                ' Puerto-Rico',
                   ' Honduras',                    ' England',
                     ' Canada',                    ' Germany',
                       ' Iran',                ' Philippines',
                      ' Italy',                     ' Poland',
                   ' Columbia',                   ' Cambodia',
                   ' Thailand',                    ' Ecuador',
                       ' Laos',                     ' Taiwan',
                      ' Haiti',                   ' Portugal',
         ' Dominican-Republic',                ' El-Salvador',
                     ' France',                  ' Guatemala',
                      ' China',                      ' Japan',
                 ' Yugoslavia',                       ' Peru',
 ' Outlying-US(Guam-USVI-etc)',                   ' Scotland',
            ' Trinadad&Tobago',                     ' Greece',
                  ' Nicaragua',                    ' Vietnam',
                       ' Hong',                    ' Ireland',
                    ' Hungary',         ' Holand-Netherlands']
Length: 42, dtype: str

In [60]:
df['income'].unique()

<StringArray>
[' <=50K', ' >50K']
Length: 2, dtype: str

# 3

In [77]:
df2=df.copy()

In [83]:
colunas_texto = df2.select_dtypes(include=['str']).columns

df2[colunas_texto] = df2[colunas_texto].apply(lambda x: x.str.strip())
#A diferença em cada coluna categórica não mudou, já que eram todas diferentes, apenas foram retirados trailing spaces.

In [110]:
colunas_num=df2.select_dtypes(include=['int','float','int64','float64']).columns
df2[colunas_num]=df2[colunas_num].replace(0,np.nan)
df2.isna().sum()
# 29 mil e 31 mil valors em capital-gain e capital-loss respectivamente

age                   0
workclass             0
fnlwgt                0
education             0
education-num         0
marital-status        0
occupation            0
relationship          0
race                  0
sex                   0
capital-gain      29849
capital-loss      31041
hours-per-week        0
native-country        0
income                0
dtype: int64

# 4

In [114]:
colunas_num=df2.select_dtypes(include=['int','float','int64','float64']).columns
minmax_scaler=MinMaxScaler()
zscore_scaler=StandardScaler()
robust_scaler=RobustScaler()

df_minmax,df_zscore,df_robust=df2.copy(),df2.copy(),df2.copy()

df_minmax[colunas_num] = minmax_scaler.fit_transform(df2[colunas_num])
df_zscore[colunas_num] = zscore_scaler.fit_transform(df2[colunas_num])
df_robust[colunas_num] = robust_scaler.fit_transform(df2[colunas_num])

df_minmax[colunas_num].describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32560.000000,32560.000000,32560.000000,2711.000000,1519.000000,32560.000000
mean,0.295639,0.120548,0.605373,0.128433,0.408576,0.402423
std,0.186858,0.071685,0.171514,0.224244,0.089639,0.125996
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.150685,0.071682,0.533333,0.033008,0.361104,0.397959
50%,0.273973,0.112793,0.600000,0.071923,0.412283,0.397959
75%,0.424658,0.152653,0.733333,0.139861,0.433706,0.448980
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [112]:
df_zscore[colunas_num].describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,3.256000e+04,3.256000e+04,3.256000e+04,2.711000e+03,1.519000e+03,3.256000e+04
mean,1.896381e-16,-7.725188e-17,5.150125e-17,-1.113909e-17,2.619512e-16,2.854392e-16
std,1.000015e+00,1.000015e+00,1.000015e+00,1.000184e+00,1.000329e+00,1.000015e+00
min,-1.582181e+00,-1.681667e+00,-3.529637e+00,-5.728431e-01,-4.559542e+00,-3.193982e+00
25%,-7.757550e-01,-6.816824e-01,-4.200266e-01,-4.256192e-01,-5.297645e-01,-3.542999e-02
50%,-1.159519e-01,-1.081858e-01,-3.132531e-02,-2.520495e-01,4.136414e-02,-3.542999e-02
75%,6.904742e-01,4.478779e-01,7.460773e-01,5.097190e-02,2.804413e-01,3.695126e-01
max,3.769555e+00,1.226855e+01,2.300883e+00,3.887412e+00,6.600047e+00,4.742893e+00

In [113]:
df_robust[colunas_num].describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32560.000000,32560.000000,32560.000000,2711.000000,1519.000000,32560.000000
mean,0.079082,0.095777,0.026863,0.528859,-0.051054,0.087494
std,0.682032,0.885314,0.857570,2.098622,1.234661,2.469524
min,-1.000000,-1.393003,-3.000000,-0.673100,-5.678689,-7.800000
25%,-0.450000,-0.507717,-0.333333,-0.364190,-0.704918,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.550000,0.492283,0.666667,0.635810,0.295082,1.000000
max,2.650000,10.957131,2.000000,8.685562,8.095082,11.800000

## Comparação de Resultados
- Z-score: Ajusta os dados para terem média igual a 0, e desvio padrão igual a 1, mas é extremamente sensível a valores extremos.
- Min-Max: Limita a faixa de valores entre 0 e 1, mas outliers forçam os limites de maneira que comprimem a maioria dos dados em uma faixa muito pequena, deixando a média, por exemplo, `0.13` em `capital-gain`.
- Robust: Demonstrou maior resiliência aos valores extremos, já que usa a mediana e interfalo interquartil (IQR), evitando que os outliers distorçam a distribuição dos dados.

# Reflexão
- Pode retornar 0 pois dados faltando não necessariamente são NaN, podendo ser 0 ou '', por exemplo.
- A mais afetada foi a robust, pois esta olha para a mediana, que é 0.
- Não, pois ao escalonar todas as colunas,poderia-se perder informações, como na coluna `fnlwgt` que é uma abreviação para "final weight" ou peso final, que é apenas um peso para que cada linha represente um número específico de pessoas, ao escalonar `fnlwgt`, o significado real da mesma é distorcido e perdido.